### ISSUE TITLE
Project V1 Feedback

### ISSUE THREAD

**Issue by annieliu2** [jhoffman12/Project#2]
Content:
-for the restaurants maybe add a rating system with 5 stars being the best
-also for the restaurants maybe group them by like different diets ex: vegan, vegetarian etc.

technical:
- in the header, you can include a drop-down of different types of restaurants instead of everything on one page
-overall, you have a lot of content, but it's kind of clutter in one space

**Comment by jhoffman12** [comment]
Thank you so much for the feedback, I will take in to consideration everything you have suggested.
