### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by mmadison1** [jhoffman12/Project#3]
I loved all of the content and information you provided! I think you just need to continue to work on the CSS to add some pop and it will be great. My only comment is that the map images seem to come up somewhat slow on the restaurant page and maybe just a suggestion is to also line up a picture of the restaurant or some type of food from there for aesthetic!

**Comment by jhoffman12** [comment]
Thanks for the suggestions, I love the idea about photos from the restaurants!
