### ISSUE TITLE
Proj v1 peer review

### ISSUE THREAD

**Issue by elitvak1** [jhoffman12/Project#4]
Great content and choice of image. Very pretty beach. I recommend making your color scheme for uniform and cohesive. The yellow background is a bit bland. The font is a little too big (paragraph body text) and the font is a little cartoony. I like your link bar at the top and the dotted border around the title of the page. 

Great information and very informative. Great job. I cant wait to see how the final turns out.

**Comment by jhoffman12** [comment]
Thanks for the suggestions, I will take them all into consideration when finishing up my final project!
